- hosts: localhost
  gather_facts: True
  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.local"
  vars:
    npm_packages_installs:
      - {name: yarn, command: yarn}
      - {name: plop, command: plop}
      - {name: typescript, command: typescript}
      - {name: ts-node, command: ts-node}
      - {name: nodemon, command: nodemon}
      - {name: prettier, command: prettier}
      - {name: husky, command: husky}
      - {name: lint-staged, command: lint-staged}
      - {name: serve, command: serve}
      - {name: npm-check, command: npm-check}

    lts_node: "16.13.1"
    dotfiles_git: "git@github.com:ultrox/dotfiles3.git"
    source_key: ".ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  pre_tasks:
    - name: Update Apt
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present

    - name: Set espanso directory on Ubuntu
      set_fact:
        espanso_dir: "{{ lookup('env', 'HOME') }}/.config/espanso"
      when: ansible_facts['distribution'] == "Ubuntu"
      tags:
        - always

    - name: Get the username running the deploy
      become: false
      local_action: command whoami
      register: result
      tags:
        - debug
        - always

    - name: Set the username env var
      set_fact:
        username: "{{ result.stdout }}"
      tags:
        - debug
        - always


  tasks:
    - include: tasks/debug.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    # - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
      include: tasks/docker.yml
    - include: tasks/exa.yml
    # - include: tasks/pacman-packages.yml
    # - include: tasks/python.yml
