- hosts: localhost

  gather_facts: True

  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.local"
  vars:
    dotfiles: "git@github.com:ultrox/dotfiles3.git"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    npm_g_pkgs:
      - yarn
      - pnpm
      - typescript-language-server
      - typscript
      - ts-node
      - '@gridsome/cli'
      - nodemon
      - prettier
      - get-graphql-schema
      - husky
      - lint-staged
      - plop
      - serve
      - tldr

  pre_tasks:
    - name: Set espanso directory on Arch
      set_fact:
        espanso_dir: "{{ lookup('env', 'HOME') }}/.config/espanso"
      when: ansible_facts['distribution'] == "Archlinux"
      tags:
        - always

    - name: Get the username running the deploy
      become: false
      local_action: command whoami
      register: result
      tags:
        - debug
        - always

    - name: Set the username env var
      set_fact:
        username: "{{ result.stdout }}"
      tags:
        - debug
        - always

    - name: Update repositories
      become: true
      pacman:
        update_cache: yes

  tasks:
    - include: tasks/debug.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/pacman-packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/python.yml
    - include: tasks/yay.yml
