- name: Creates n directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/n"
    state: directory
  tags:
    - install
    - node

- name: Install nodejs and npm on Arch
  become: true
  when: ansible_distribution == "Archlinux"
  pacman:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: Install N with npm
  become_user: "{{ lookup('vars', 'username') }}"
  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.config/n"
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install node on Mac
  when: ansible_distribution == "MacOSX"
  become_user: "{{ lookup('vars', 'username') }}"
  community.general.homebrew:
    name: node
    state: present
  tags:
    - install
    - node

- name: Install desired version of Node using N
  become_user: "{{ lookup('vars', 'username') }}"
  command: "{{ lookup('env', 'HOME') }}/.config/n/bin/n 15"
  tags:
    - install
    - node
