- name: Setup Node
  tags:
    - install
    - node
    - npm
  become_user: "{{ lookup('vars', 'username') }}"
  block:
  - name: Download FNM
    ansible.builtin.get_url: 
      url: https://fnm.vercel.app/install
      dest: "/tmp/fnm-install.sh"

  - name: Changing perm of "of fnm file", adding "+x"
    file: dest=/tmp/fnm-install.sh mode=+x

  - name: Install FNM
    ansible.builtin.script: 
      cmd: "{{ lookup('env', 'HOME') }}/fnm-install.sh --skip-shell"

  - name: Install Current LTS Node Version
    ansible.builtin.shell: 
      cmd: zsh -ic "fnm install {{ node_lts }}"

  - name: Instruct FNM To Use Node LTS Version
    ansible.builtin.shell: 
      cmd: zsh -ic "fnm use {{ node_lts }}"

  - name: Install Prettier Globally
    ansible.builtin.shell: 
      cmd: zsh -ic "npm install -g prettier"

  - name: Install common npm utilities
    become_user: "{{ lookup('vars', 'username') }}"
    npm: 'name={{item}} state=present global=yes'
    with_items:
      - yarn
      - pnpm
      - typscript
      - ts-node
      - typescript-language-server
      - diagnostic-languageserver
      - nodemon
      - prettier
      - get-graphql-schema
      - husky
      - lint-staged
      - plop
      - serve

