- name: Install Vim-Plug
  shell: |
    curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim 
    --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - dotfiles
    - neovim
- name: Install vim Plugins
  shell: nvim +PlugInstall +qall +silent
  tags:
    - install
    - dotfiles
    - neovim
