# - name: Install Vim-Plug
#   shell: |
#     curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#   tags:
#     - install
#     - dotfiles
#     - neovim
# - name: Install vim Plugins
#   shell: nvim +PlugInstall +qall +silent
#   tags:
#     - install
#     - dotfiles
#     - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    depth: 1
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags: 
    - neovim

- name: Build Neovim
  become: true
  ansible.builtin.shell: 
    cmd: cd {{ lookup('env', 'HOME') }}/neovim && make -j 20
  tags: 
    - neovim

- name: Install Neovim
  become: true
  ansible.builtin.shell: 
    cmd: cd {{ lookup('env', 'HOME') }}/neovim && make install
  tags: 
    - neovim

- name: Install Packer (Lua Package Manager)
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
  tags: 
    - neovim

- name: Install Neovim Plugins Via Packer
  ansible.builtin.shell:
    cmd: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  tags: 
    - neovim
