- name: Install System Packages
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  pacman: name={{item}}
  with_items:
    - yay
    - unrar
    - unzip
    - gnupg
    - trash-cli
    - openssh
    - maim
    - peek
    - htop
    - jq
    - neovim
    - tmux
    - tree
    - flameshot
    - rofi
    - kitty
    - vlc
    - stow
    - diff-so-fancy
    - github-cli
    - tree-sitter
    - ttf-nerd-fonts-symbols
    - docker
    - docker-compose
    - xscape
    - firefox
    - firefox-developer-edition
    - gparted
    - obs-studio
    - pavucontrol
    - pulseaudio-bluetooth
    - pulsemixer
    - xclip
    - exa
    - bat
    - fzf
    - youtube-dl
    - zathura
    - zathura-pdf-mupdf
    - ffmpeg
    - ffmpegthumbnailer
    - neofetch
    - nautilus
    - ack
    - pyenv
    - dunst
    - acpi
    - lua
    - luarocks
    - adobe-source-han-sans-jp-fonts
    - aegisub
    - arandr
    - baobab
    - bleachbit
    - blueman
    - brightnessctl
    - code
    - dbeaver
    - fcitx-configtool
    - fcitx-mozc
    - fcitx-qt5
    - feh
    - kdenlive
    - mpd
    - ncmpcpp
    - newsboat
    - rclone
    - redshift
    - remmina
    - signal-desktop
    - tlp
    - udiskie

  tags:
    - install
    - pacman
    - linux


- name: "Ensure directory .local/bin"
  file: 
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: "directory"
  tags: 
    - dygma
    - install

    
- name: "Ensure directory exists"
  file: 
    path: "{{ lookup('env', 'HOME') }}/packages"
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: "directory"
  tags: 
    - install
    - dygma

- name: "Download Raise keyboard configure"
  get_url:
    url: "https://github.com/Dygmalab/Bazecor/releases/download/v0.3.4/Bazecor-0.3.4.AppImage"
    dest: "{{ lookup('env', 'HOME') }}/packages/dygma-configurator"
  tags:
    - install
    - pacman
    - dygma

- name: "Make configuration executable"
  file:
    path: "{{ lookup('env', 'HOME') }}/packages/dygma-configurator"
    mode: 0755
  tags:
    - install
    - pacman
    - dygma

- name: "Symling to .local/bin"
  file:
    src: "{{ lookup('env', 'HOME') }}/packages/dygma-configurator"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/dygma-configurator"
    state: link
  tags:
    - link
    - install
    - pacman
    - dygma

