## Python 3
- name: Setup Python 3
  become_user: "{{ lookup('vars', 'username') }}"
  # when: ansible_distribution == "Archlinux"
  tags: 
    - install
    - python
  block:
  - name: Install python version 3.9.0 with pyenv
    command: pyenv install -f 3.9.0

  - name: Set Python 3.9.0 as global version
    command: pyenv global 3.9.0

  - name: pip install virtualenvwrapper
    pip:
      name: virtualenvwrapper

  - name: Creates virtualenv directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.config/virtualenvs"
      state: directory

  - name: Create nvim python3 virtualenv
    shell: . "{{ lookup('env', 'HOME') }}/.local/bin/virtualenvwrapper.sh" && mkvirtualenv neovim-python-3-9-0 && pip install pynvim
    environment:
      WORKON_HOME: "{{ lookup('env', 'HOME') }}/.config/virtualenvs"
