## Python 3

- name: Install python version 3.9.0 with pyenv
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  command: pyenv install -f 3.9.0
  tags:
    - install
    - python
    - python3

- name: Set Python 3.9.0 as global version
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  command: pyenv global 3.9.0
  tags:
    - install
    - python
    - python3

- name: pip install virtualenvwrapper
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  pip:
    name: virtualenvwrapper
  tags:
    - install
    - python
    - python3

- name: Creates virtualenv directory
  become_user: "{{ lookup('vars', 'username') }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/virtualenvs"
    state: directory
  tags:
    - install
    - python
    - python3

- name: Create nvim python3 virtualenv
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  shell: . "{{ lookup('env', 'HOME') }}/.local/bin/virtualenvwrapper.sh" && mkvirtualenv neovim-python-3-9-0 && pip install pynvim
  environment:
    WORKON_HOME: "{{ lookup('env', 'HOME') }}/.config/virtualenvs"
  tags:
    - install
    - python
    - python3

## Python 2

- name: Install python version 2.7.18 with pyenv
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  command: pyenv install -f 2.7.18
  tags:
    - install
    - python
    - python2

- name: Set Python 2.7.18 as global version
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  command: pyenv global 2.7.18
  tags:
    - install
    - python
    - python2

- name: pip install virtualenvwrapper
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  pip:
    name: virtualenvwrapper
    executable: pip2
  tags:
    - install
    - python
    - python2

- name: Create nvim python2 virtualenv
  when: ansible_distribution == "Archlinux"
  become_user: "{{ lookup('vars', 'username') }}"
  shell: . "{{ lookup('env', 'HOME') }}/.local/bin/virtualenvwrapper.sh" && mkvirtualenv neovim-python-2-7-18 && pip install pynvim
  environment:
    WORKON_HOME: "{{ lookup('env', 'HOME') }}/.config/virtualenvs"
  tags:
    - install
    - python
    - python2
