- name: Install packages
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
  yay: name={{item}}
  with_items:
    - key-mapper-git
    - postman-bin
    - slack-desktop
    - google-chrome
      #- visual-studio-code-bin
  tags:
    - install
    - yay
    - linux

